# Change these first
owner: michael-squadc # Your GitHub organization or username, where this repository lives
repo: squadc-upptime # The name of this repository

sites:
  - name: Squad-C Website
    url: https://www.squadc.com
    maxResponseTime: 5000
  - name: Squad-C Website DE
    url: https://www.squadc.com/de
    maxResponseTime: 5000
    __dangerous__body_down_if_text_missing: 'XXXXXXXXXXXXXXXX'
assignees:
  - michael-squadc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /squadc-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://$OWNER.github.io/$REPO/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
